apiVersion: v1
name: dts-odoo
version: 13.0.11
appVersion: 13.0.7
description: A suite of web based open source business apps.
home: https://www.odoo.com/
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-110x117.png
keywords:
- odoo
- crm
- www
- http
- web
sources:
- https://github.com/odoo/docker
maintainers:
- name: Eric Dube
  email: eric.dube@hrsdc-rhdcc.gc.ca
engine: gotpl
