apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mtsbackup-confluence
spec:
  storageClassName: "default"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: mtsbackupsecret-confluence
    shareName: {{ .Values.confluence.backupsharename }}
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
