apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: confluence-ingress
 namespace: default
 annotations:
   kubernetes.io/ingress.class: traefik
spec:
 rules:
 - host: {{ .Values.confluence.url }}
   http:
     paths:
     - backend:
         serviceName: mtsconfluence
         servicePort: 80
