apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: confluence-ingress
 annotations:
   kubernetes.io/ingress.class: traefik
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
            backend:
              serviceName: mtsconfluence
              servicePort: http
  {{- end }}
