apiVersion: v1
kind: Pod
metadata:
  name: mtsconfluence
  creationTimestamp: null
  labels:
    service: mtsconfluence
spec:
  restartPolicy: Always
  containers:
  - name: mtsjira
    image: mtscontainers.azurecr.io/mtsconfluence
    ports:
    - containerPort: 8090

