---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mtsbackup-confluence
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "default"
  volumeName: pv-mtsbackup-confluence
