apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mtsconfluence
  name: mtsconfluence
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8090
  type: LoadBalancer
  selector:
    service: mtsconfluence
status:
  loadBalancer: {}
