apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
{{- end }}
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  type: LoadBalancer
  selector:
  selector:
    app: {{ template "postgresql.name" . }}
    release: {{ .Release.Name }}
status:
  loadBalancer: {}





