apiVersion: v1
name: dts-consul
version: 0.16.2
description: Install and configure Consul on Kubernetes.
home: https://www.consul.io
sources:
  - https://github.com/hashicorp/consul
  - https://github.com/hashicorp/consul-helm
  - https://github.com/hashicorp/consul-k8s
