{{ if .Values.apache.mountHTDocs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-htdocs-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.apache.azureStorageAccountName }}
  azurestorageaccountkey: {{ .Values.apache.azureStorageAccountKey }}
{{ end }}
