{{ if .Values.apache.mountHTDocs }}
apiVersion: v1
kind: Secret
metadata:
{{ if .Values.apache.htdocsSecretName }}
  name: {{ .Values.apache.htdocsSecretName }} 
{{ else }} 
  name: {{ template "fullname" . }}-htdocs-secret
{{ end }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.apache.azureStorageAccountName }}
  azurestorageaccountkey: {{ .Values.apache.azureStorageAccountKey }}
{{ end }}
