kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jira-attachments
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeName: pv-jira-attachments-{{ .Values.jira.environment }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jira-attachments-{{ .Values.jira.environment }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: mtsbackupsecret-jira
    shareName: {{ .Values.jira.attachmentsharename }}
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000

