---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jira-attachments
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "default"
  volumeName: pv-jira-attachments
