apiVersion: v1
kind: Pod
metadata:
  name: mtsjira
  creationTimestamp: null
  labels:
    service: mtsjira
spec:
  restartPolicy: Always
  containers:
  - name: mtsjira
    image: mtscontainers.azurecr.io/mtsjira
    ports:
    - containerPort: 8080

