apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: jira-ingress
 annotations:
   kubernetes.io/ingress.class: traefik
spec:
 rules:
 - host: {{ .Values.jira.url }}
   http:
     paths:
     - backend:
         serviceName: mtsjira
         servicePort: 80
