apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mtsjira
  name: mtsjira
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    service: mtsjira
status:
  loadBalancer: {}
