# Default values for mts-jira.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

jira:
   url: jira.mobiletechnology.solutions
   azurestorageaccountname: accountname
   azurestorageaccountkey: accountkey
   attachmentsbackupfolderpath: prod/jira/data
   attachmentsbackupfoldermountpath: /var/atlassian/application-data/jira/data
   attachmentsharename: jira-attachments
   backupfolderpath: prod/jira
   backupsharename: backupfiles
   backupfoldermountpath: /var/atlassian/application-data/jira/export
   createPersistentVolume: "true"
   image: mtscontainers.azurecr.io/mtsjira
   environment: dev
   resources: 
     mincpu: 2
     minmemory: 4Gi
     jvmminmemory: 2048m
     jvmmaxmemory: 4096m



