{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-notls
spec:
  entryPoints:
    - web
  routes:
  - match: {{ .Values.ingressRoute.host }}  
    kind: Rule
    services: 
    - name: {{ $fullName }}
      port: {{ .Values.service.port }}
    # middlewares:
    # - name: redirect-to-https

---

{{- $fullName := include "fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-tls
spec:
  entryPoints:
    - websecure
  routes:
  - match: {{ .Values.ingressRoute.host }}  
    kind: Rule
    services: 
    - name: {{ $fullName }}
      port: {{ .Values.service.port }}
  {{- if .Values.ingressRoute.tls }}
  tls: {}
  {{- end }}
{{- end }}