{{- $fullName := include "fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  entryPoints:
    - web
  routes:
  {{- range .Values.ingress.hosts }} 
  - match: Host(`{{ . }}`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ $servicePort }}
  {{- end }}