{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name | quote }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
  {{ if .Values.networkPolicy.ingressCidrBlock }}
    - ipBlock:
        cidr: {{ .Values.networkPolicy.ingressCidrBlock }}
        {{ if .Values.networkPolicy.ingressCidrBlockException }} 
        except:
        - {{ .Values.networkPolicy.ingressCidrBlockException }}
        {{ end }}
  {{ end }}
  {{ if .Values.networkPolicy.ingressPodMatchLabels }}
    - podSelector:
        matchLabels:
        {{- range $key, $value := .Values.networkPolicy.ingressPodMatchLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }} 
  {{ end }}
    ports:
    - protocol: TCP
      port: 5601
  egress:
  - to:
    - podSelector:
        matchLabels:
        {{- range $key, $value := .Values.networkPolicy.egressPodMatchLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }} 
    ports:
    - protocol: TCP
      port: 9200
    - protocol: TCP
      port: 9300
{{ end }}