apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.name }}
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Values.mariadb.name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mariadb.name }}-pv
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  storageClassName: {{ .Values.mariadb.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size | quote }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: {{ .Values.mariadb.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mariadb.name }}
    spec:
      containers:
        - name: {{ .Values.mariadb.name }}
          image: {{ .Values.mariadb.image }}
          ports:
          - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mariadbql/data
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.dbname }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.dbusername }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootpassword }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.dbpassword }}
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mariadb.name }}-pv
