{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "graylog.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "elasticsearch.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      component: "{{ .Values.master.name }}"
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
  {{ if .Values.networkPolicy.ingressCidrBlock }}
    - ipBlock:
        cidr: {{ .Values.networkPolicy.ingressCidrBlock }}
        {{ if .Values.networkPolicy.ingressCidrBlockException }} 
        except:
        - {{ .Values.networkPolicy.ingressCidrBlockException }}
        {{ end }}
  {{ end }}
  {{ if .Values.networkPolicy.ingressPodMatchLabels }}
    - podSelector:
        matchLabels:
        {{- range $key, $value := .Values.networkPolicy.ingressPodMatchLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }} 
  {{ end }}
    ports:
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 9200
    - protocol: TCP
      port: 9300
    egress:
    - to:
      - podSelector:
          matchLabels:
          {{- range $key, $value := .Values.networkPolicy.egressPodMatchLabels }}
          {{ $key }}: {{ $value | quote }}
          {{- end }} 
      ports:
      - protocol: TCP
        port: 9000
{{ end }}