# Default values for mts-marcus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deploymentName: nginx-deployment

serviceName: nginx-service

ingressName: nginx-ingress

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /nginx
  host: nginx-marcusrd.esdc.online
nodeSelector: {}

tolerations: []

affinity: {}
