name: mts-apache
version: 0.2.2
appVersion: 2.4.37
description: Chart for Apache HTTP Server -based off of Bitnami chart
keywords:
- apache
- http
- https
- www
- web
- reverse proxy
home: https://httpd.apache.org
maintainers:
- name: MTS
  email: gocmts@gmail.com
engine: gotpl
