apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.postgres.name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.postgres.name }}-pv
  labels:
    app: {{ .Values.postgres.name }}
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgsql
spec:
  replicas: {{ .Values.postgres.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }}
          ports:
          - containerPort: 5432
          volumeMounts:
            - name: pgsql-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: {{ .Values.postgres.dbusername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.dbpassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbname }}
      volumes:
      - name: pgsql-storage
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.name }}-pv
