apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: discourse-postgresql
  name: discourse-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discourse-postgresql
  template:
    metadata:
      labels:
        app: discourse-postgresql
    spec:
      containers:
      - image: bitnami/postgresql
        name: discourse-postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse-postgresql
  name: discourse-postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: discourse-postgresql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: discourse-redis
  name: discourse-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discourse-redis
  template:
    metadata:
      labels:
        app: discourse-redis
    spec:
      containers:
      - image: bitnami/redis
        name: discourse-redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes" 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse-redis
  name: discourse-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: discourse-redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: discourse-discourse
  name: discourse-discourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discourse-discourse
  template:
    metadata:
      labels:
        app: discourse-discourse
    spec:
      containers:
      - image: bitnami/discourse
        name: discourse-discourse
        env:
        - name: DISCOURSE_USERNAME
          value: gocmts
        - name: DISCOURSE_PASSWORD
          value: MTS@dmin1!
        - name: DISCOURSE_PASSWORD
          value: MTS@dmin1!
        - name: DISCOURSE_EMAIL
          value: gocmts@gmail.com
        - name: DISCOURSE_SITENAME
          value: ESDC - MTS
        - name: DISCOURSE_HOSTNAME
          value: discourse-benrd.mobiletechnology.solutions
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: gocmts
        - name: SMTP_PASSWORD
          value: MTS@dmin1!
        - name: POSTGRESQL_HOST
          value: discourse-postgresql
        - name: POSTGRESQL_ROOT_USER
          value: postgres
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
          value: bitnami_application
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
          value: bn_discourse
        - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
          value: bitnami1
        - name: DISCOURSE_POSTGRESQL_NAME
          value: bitnami_application
        - name: DISCOURSE_POSTGRESQL_USERNAME
          value: bn_discourse
        - name: DISCOURSE_POSTGRESQL_PASSWORD
          value: bitnami1
        - name: DISCOURSE_HOSTNAME
          value: discourse-benrd.mobiletechnology.solutions
        - name: REDIS_HOST
          value: discourse-redis
        - name: REDIS_PORT_NUMBER
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse-discourse
  name: discourse-discourse
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: discourse-discourse
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: discourse-sidekiq
  labels:
    app: discourse-sidekiq
spec:
  containers:
  - name: sidekiq
    image: bitnami/discourse
    args:
    - nami
    - start
    - --foreground
    - discourse-sidekiq
    env:
    - name: POSTGRESQL_HOST
      value: discourse-postgresql
    - name: POSTGRESQL_ROOT_USER
      value: postgres
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_NAME
      value: bitnami_application
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
      value: bn_discourse
    - name: POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD
      value: bitnami1
    - name: DISCOURSE_POSTGRESQL_NAME
      value: bitnami_application
    - name: DISCOURSE_POSTGRESQL_USERNAME
      value: bn_discourse
    - name: DISCOURSE_POSTGRESQL_PASSWORD
      value: bitnami1
    - name: DISCOURSE_HOST
      value: discourse-discourse
    - name: DISCOURSE_PORT
      value: "3000"
    - name: DISCOURSE_HOSTNAME
      value: discourse-benrd.mobiletechnology.solutions
    - name: REDIS_HOST
      value: test-redis
    - name: REDIS_PORT_NUMBER
      value: "6379"
    - name: SMTP_HOST
      value: smtp.gmail.com
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_USER
      value: gocmts
    - name: SMTP_PASSWORD
      value: MTS@dmin1!
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discourse-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
 rules:
  - host: discourse-benrd.mobiletechnology.solutions
    http:
      paths:
      - backend:
          serviceName: discourse-discourse
          servicePort: 3000
