name: mts-pgsql
version: 0.1.1
appVersion: 10.6.0
description: MTS Version of Postgres chart, based off of 3.8.0. This includes the mts-disk chart in requirements.
keywords:
- postgresql
- postgres
- database
- sql
- replication
- cluster
home: https://www.postgresql.org/
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
engine: gotpl
