{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "odoo.name" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "odoo.name" . }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    {{- if .Values.networkPolicy.ingressRules }}
    {{ toYaml .Values.networkPolicy.ingressRules | nindent 4 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 12201
    egress:
    - to:
      - podSelector:
          matchLabels:
          {{- range $key, $value := .Values.networkPolicy.egressPodMatchLabels }}
          {{ $key }}: {{ $value | quote }}
          {{- end }} 
      ports:
      - protocol: TCP
        port: 9200
      - protocol: TCP
        port: 9300
      - protocol: TCP
        port: 27017
{{ end }}