# Default values for mts-confluence.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

confluence:
   image: mtscontainers.azurecr.io/mtsconfluence:0.3.1
   url: confluence.mobiletechnology.solutions
   azurestorageaccountname: accountname
   azurestorageaccountkey: accountkey
   attachmentsharename: confluence-attachments
   attachmentsbackupfolderpath: prod/confluence/attachments
   attachmentsbackupfoldermountpath: /var/atlassian/application-data/confluence/attachments
   backupfolderpath: prod/confluence
   backupsharename: backupfiles
   backupfoldermountpath: /var/atlassian/application-data/confluence/backups
   createPersistentVolume: "true"
   environment: dev

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: "true"
  annotations: {}
    # kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
