apiVersion: batch/v1
kind: Job
metadata:
  name: elasticusers
spec:
  template:
    spec:
      containers:
      - name: createusers
        image: {{ .Values.elasticUtil.image }}
        env: {{ toYaml .Values.elasticUtil.extraEnvs | nindent 10 }}
      restartPolicy: Never
  backoffLimit: 4
