{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "uname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "uname" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    esMajorVersion: "{{ include "esMajorVersion" . }}"
spec:
  podSelector:
    matchLabels:
      app: elasticsearch-master
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
  {{ if .Values.networkPolicy.ingressCidrBlock }}
    - ipBlock:
        cidr: {{ .Values.networkPolicy.ingressCidrBlock }}
        {{ if .Values.networkPolicy.ingressCidrBlockException }} 
        except:
        - {{ .Values.networkPolicy.ingressCidrBlockException }}
        {{ end }}
  {{ end }}
  {{ if .Values.networkPolicy.ingressPodMatchLabels }}
        {{- range $key, $value := .Values.networkPolicy.ingressPodMatchLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }} 
  {{ end }}
    ports:
    - protocol: TCP
      port: 9200
    - protocol: TCP
      port: 9300
  egress:
  - to:
    - podSelector:
        matchLabels:
        {{- range $key, $value := .Values.networkPolicy.egressPodMatchLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }} 
    ports:
    - protocol: TCP
      port: http
{{ end }}