
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mtsandroidemulator
  name: mtsandroidemulator
spec:
  ports:
  - name: "4723"
    port: 4723
    targetPort: 4723
  - name: "22"
    port: 22
    targetPort: 22
  type: LoadBalancer
  selector:
    service: mtsandroidemulator
status:
  loadBalancer: {}
