apiVersion: v1
kind: Secret
metadata:
  name: elastic-certificates
  labels:
    app.kubernetes.io/name: {{ template "elk.name" . }}
    helm.sh/chart: {{ template "elk.chart" . }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
type: Opaque
data:
{{ (.Files.Glob "certs/elastic.p12").AsSecrets | indent 2 }}