apiVersion: v1
kind: Service
metadata:
  name: {{ template "graylog.fullname" . }}-udp
  labels:
    name: graylog-udp
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    component: graylog-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    graylog: "true"
  ports:
  - name: udp-input
    protocol: UDP
    port: 12201
    nodePort: 31301
  type: LoadBalancer


