apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    chart: {{ include "mts-marcus.chart" . }}
spec:
  selector:
    app: {{ .Values.deploymentName }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  
