{{- if .Values.ingress.enabled -}}
{{- $fullName := include "jenkins.fullname" . -}}
{{- $servicePort := .Values.Master.ServicePort -}}
{{- $ingressPath := .Values.Master.Ingress.Path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
{{- if .Values.Master.Ingress.TLS }}
  tls:
{{ toYaml .Values.Master.Ingress.TLS | indent 4 }}
{{- end -}}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
