apiVersion: v1
kind: ConfigMap
metadata:
  name: dynatrace-crd
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
  data:
    customResource.yaml |-
      {{.Files.Get "../files/customResource.yaml" }}